extends Node

signal locale_changed()
signal start_requested()
signal game_started()
signal game_ended()
signal tutorial_step_completed(step: String)
signal player_jumped(wall_jump: bool)
signal player_landed()
signal player_attacked()
signal player_damaged(damage: int, attack_direction: float)
signal player_health_changed(health: int, was_lost: bool)
signal player_entered_screen(index: int)
signal player_death_finished()
signal screen_transition_started(old_screen_index: int)
signal screen_transition_ended(new_screen_index: int)
signal enemy_damaged(enemy: Enemy, amount: int, attack_direction: float)
signal time_changed(seconds: int)
signal fade_completed()
