extends Node

signal locale_changed()
signal cheat_code_entered(cheat_code: CheatCodeObserver.CheatCode)
signal start_requested(game_options: GameOptions)
signal game_started()
signal game_paused()
signal game_resumed()
signal princess_saved()
signal game_ended(show_credits: bool)
signal tutorial_step_completed(step: String)
signal player_jumped(wall_jump: bool)
signal player_landed()
signal player_attacked()
signal player_damaged(damage: int, attack_direction: float)
signal player_caught_fly(fly: Fly)
signal player_health_changed(health: int, was_lost: bool)
signal player_entered_screen(index: int)
signal player_death_finished()
signal player_transformed()
signal screen_ready(screen: Node2D)
signal screen_transition_started(old_screen_index: int)
signal screen_transition_ended(new_screen_index: int)
signal object_damaged(enemy: Enemy, attack_direction: float)
signal enemy_damaged(enemy: Enemy, amount: int, attack_direction: float)
signal time_changed(seconds: int)
signal fade_completed()
signal dialog_opened()
signal dialog_continued()
signal dialog_event(event_name: String)
signal dialog_event_ended()
signal dialog_closed()
